- name: Vérifier si le répertoire {{ directory }} existe
  command: hadoop fs -test -d {{ directory }}
  register: dir_exists
  ignore_errors: yes
  changed_when: False

- name: Créer le répertoire {{ directory }}
  command: hadoop fs -mkdir -p {{ directory }}
  when: dir_exists.rc != 0
  register: mkdir_output
  changed_when: True

- name: Afficher le message approprié
  debug:
    msg: >
      {{
        "Le répertoire " + directory + " existe déjà."
        if dir_exists.rc == 0
        else "Le répertoire " + directory + " a été créé avec succès."
      }}
