- name: Vérifier si la planification Daily_30 existe
  shell: maprcli schedule list -output verbose | grep -w '^Daily_30$'
  register: Daily_30_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification Daily_30
  command: maprcli schedule create -schedule '{"name":"Daily_30","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: Daily_30_exists.rc != 0
  register: Daily_30_creation
  changed_when: True

- name: Afficher le message pour Daily_30
  debug:
    msg: >
      {{
        "La planification Daily_30 existe déjà." 
        if Daily_30_exists.rc == 0 
        else "La planification Daily_30 a été créée avec succès."
      }}
  when: Daily_30_exists.rc == 0 or Daily_30_creation.changed


- name: Vérifier si la planification Weekly_90 existe
  shell: maprcli schedule list -output verbose | grep -w '^Weekly_90$'
  register: Weekly_90_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification Weekly_90
  command: maprcli schedule create -schedule '{"name":"Weekly_90","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: Weekly_90_exists.rc != 0
  register: Weekly_90_creation
  changed_when: True

- name: Afficher le message pour Weekly_90
  debug:
    msg: >
      {{
        "La planification Weekly_90 existe déjà." 
        if Weekly_90_exists.rc == 0 
        else "La planification Weekly_90 a été créée avec succès."
      }}
  when: Weekly_90_exists.rc == 0 or Weekly_90_creation.changed


- name: Vérifier si la planification monthly_180 existe
  shell: maprcli schedule list -output verbose | grep -w '^monthly_180$'
  register: monthly_180_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification monthly_180
  command: maprcli schedule create -schedule '{"name":"monthly_180","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: monthly_180_exists.rc != 0
  register: monthly_180_creation
  changed_when: True

- name: Afficher le message pour monthly_180
  debug:
    msg: >
      {{
        "La planification monthly_180 existe déjà." 
        if monthly_180_exists.rc == 0 
        else "La planification monthly_180 a été créée avec succès."
      }}
  when: monthly_180_exists.rc == 0 or monthly_180_creation.changed
