- name: Vérifier si la planification "{{ schedule.name }}" existe
  shell: maprcli schedule list -output verbose | grep -E '^{{ schedule.name }}\s+'
  register: planification_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification "{{ schedule.name }}"
  command: maprcli schedule create -schedule '{{ schedule.schedule }}'
  when: planification_exists.rc != 0
  register: planification_creation
  changed_when: True

- name: Afficher le message pour "{{ schedule.name }}"
  debug:
    msg: >
      {{
        "La planification " + schedule.name + " existe déjà."
        if planification_exists.rc == 0
        else "La planification " + schedule.name + " a été créée avec succès."
      }}
