- name: Vérifier si la planification Daily_30 existe
  shell: maprcli schedule list -output verbose | grep -E '^Daily_30\s+'
  register: Daily_30_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification Daily_30
  command: maprcli schedule create -schedule '{"name":"Daily_30","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: Daily_30_exists.rc != 0
  register: Daily_30_creation
  changed_when: True

- name: Afficher le message pour Daily_30
  debug:
    msg: >
      {{
        "La planification Daily_30 existe déjà." 
        if Daily_30_exists.rc == 0 
        else "La planification Daily_30 a été créée avec succès."
      }}
  when: Daily_30_exists.rc == 0 or Daily_30_creation.changed


- name: Vérifier si la planification Weekly_90 existe
  shell: maprcli schedule list -output verbose | grep -E '^Weekly_90\s+'
  register: Weekly_90_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification Weekly_90
  command: maprcli schedule create -schedule '{"name":"Weekly_90","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: Weekly_90_exists.rc != 0
  register: Weekly_90_creation
  changed_when: True

- name: Afficher le message pour Weekly_90
  debug:
    msg: >
      {{
        "La planification Weekly_90 existe déjà." 
        if Weekly_90_exists.rc == 0 
        else "La planification Weekly_90 a été créée avec succès."
      }}
  when: Weekly_90_exists.rc == 0 or Weekly_90_creation.changed


- name: Vérifier si la planification Monthly_180 existe
  shell: maprcli schedule list -output verbose | grep -E '^Monthly_180\s+'
  register: Monthly_180_exists
  ignore_errors: yes
  changed_when: False

- name: Créer la planification Monthly_180
  command: maprcli schedule create -schedule '{"name":"Monthly_180","rules":[{"frequency":"monthly","retain":"30d","time":15}]}'
  when: Monthly_180_exists.rc != 0
  register: Monthly_180_creation
  changed_when: True

- name: Afficher le message pour Monthly_180
  debug:
    msg: >
      {{
        "La planification Monthly_180 existe déjà." 
        if Monthly_180_exists.rc == 0 
        else "La planification Monthly_180 a été créée avec succès."
      }}
  when: Monthly_180_exists.rc == 0 or Monthly_180_creation.changed
