- name: Vérifier si le volume "{{ volume.name }}" existe
  command: maprcli volume info -name "{{ volume.name }}"
  register: volume_exists
  ignore_errors: yes
  changed_when: False

- name: Créer le volume "{{ volume.name }}"
  command: maprcli volume create -name "{{ volume.name }}" -path "{{ volume.path }}"
  when: volume_exists.rc != 0
  register: volume_creation
  changed_when: True

- name: Afficher le message pour "{{ volume.name }}"
  debug:
    msg: >
      {{
        "Le volume " + volume.name + " existe déjà."
        if volume_exists.rc == 0
        else "Le volume " + volume.name + " a été créé avec succès."
      }}
