- name: Vérifier si le snapshot volume-raw-snapshot existe
  command: maprcli volume snapshot list -volume volume-raw-data
  register: snapshot_list
  ignore_errors: yes
  changed_when: False

- name: Créer le snapshot volume-raw-snapshot
  command: maprcli volume snapshot create -volume volume-raw-data -snapshotname volume-raw-snapshot -retain 30d
  when: "'volume-raw-snapshot' not in snapshot_list.stdout"
  register: snapshot_creation
  changed_when: True

- name: Afficher le message pour le snapshot volume-raw-snapshot
  debug:
    msg: >
      {{
        "Le snapshot volume-raw-snapshot a été créé avec succès."
        if snapshot_creation.changed 
        else "Le snapshot volume-raw-snapshot existe déjà."
      }}
  when: snapshot_list.rc != 0 or snapshot_creation.changed

- name: Vérifier si le snapshot volume-clean-snapshot existe
  command: maprcli volume snapshot list -volume volume-clean-data
  register: snapshot_list
  ignore_errors: yes
  changed_when: False

- name: Créer le snapshot volume-clean-snapshot
  command: maprcli volume snapshot create -volume volume-clean-data -snapshotname volume-clean-snapshot -retain 30d
  when: "'volume-clean-snapshot' not in snapshot_list.stdout"
  register: snapshot_creation
  changed_when: True

- name: Afficher le message pour le snapshot volume-clean-snapshot
  debug:
    msg: >
      {{
        "Le snapshot volume-clean-snapshot a été créé avec succès."
        if snapshot_creation.changed 
        else "Le snapshot volume-clean-snapshot existe déjà."
      }}
  when: snapshot_list.rc != 0 or snapshot_creation.changed
- name: Vérifier si le snapshot volume-modeled-snapshot existe
  command: maprcli volume snapshot list -volume volume-modeled-data
  register: snapshot_list
  ignore_errors: yes
  changed_when: False

- name: Créer le snapshot volume-modeled-snapshot
  command: maprcli volume snapshot create -volume volume-modeled-data -snapshotname volume-modeled-snapshot -retain 30d
  when: "'volume-modeled-snapshot' not in snapshot_list.stdout"
  register: snapshot_creation
  changed_when: True

- name: Afficher le message pour le snapshot volume-modeled-snapshot
  debug:
    msg: >
      {{
        "Le snapshot volume-modeled-snapshot a été créé avec succès."
        if snapshot_creation.changed 
        else "Le snapshot volume-modeled-snapshot existe déjà."
      }}
  when: snapshot_list.rc != 0 or snapshot_creation.changed